apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld2
spec:
  selector:
    matchLabels:
      app: helloworld2
  replicas: 1 
  template: 
    metadata:
      labels:
        app: helloworld2
    spec:
      containers:
      - name: helloworld2
        image: nginxdemos/hello
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: clusterip2
spec:
  type: ClusterIP
  selector:
    app: helloworld2
  ports:
    - port: 8080
      targetPort: 80