apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld3
spec:
  selector:
    matchLabels:
      app: helloworld3
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: helloworld3
    spec:
      containers:
      - name: helloworld3
        image: jfxs/hello-world
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: clusterip3
spec:
  type: ClusterIP
  selector:
    app: helloworld3
  ports:
    - port: 8080        # Les autres services du cluster utilisent ce port
      targetPort: 8080    # Le port de nginx dans le conteneur