Vagrant.configure("2") do |config|
	config.vm.define "server" do |server|
	  server.vm.hostname = "pgouasmiS"
	  server.vm.box = "debian/bookworm64"
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = "1"
		vb.name = "IoT-server"
	  end
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.provision "shell", path: "./scripts/provision_server.sh"
	end
end