global:
  hosts:
    domain: gitlab.k3d.local
    https: false
  ingress:
    configureCertmanager: false
    class: "traefik"
  edition: ce

certmanager:
  install: false

nginx-ingress:
  enabled: false

gitlab-runner:
  install: true
  runners:
    privileged: true

persistence:
  storageClass: "local-path"

postgresql:
  persistence:
    size: 8Gi

redis:
  persistence:
    size: 2Gi

minio:
  persistence:
    size: 10Gi

gitlab:
  gitaly:
    persistence:
      size: 10Gi
  toolbox:
    backups:
      objectStorage:
        backend: s3